apiVersion: apps/v1
kind: Deployment
metadata:
  name: placeholder-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: placeholder
  template:
    metadata:
      labels:
        app: placeholder
    spec:
      containers:
        - name: placeholder
          image: nginxdemos/hello
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: placeholder-service
spec:
  type: NodePort
  selector:
    app: placeholder
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30080
