apiVersion: apps/v1
kind: Deployment
metadata:
  name: fundraiser-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fundraiser
  template:
    metadata:
      labels:
        app: fundraiser
    spec:
      containers:
        - name: fundraiser
          image: addy1015/fundraiser-app:latest
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: fundraiser-service
spec:
  type: NodePort
  selector:
    app: fundraiser
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30080
