apiVersion: apps/v1
kind: Deployment
metadata:
  name: placeholder-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: placeholder
  template:
    metadata:
      labels:
        app: placeholder
    spec:
      containers:
        - name: placeholder
          image: cicd-placeholder-app:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000

---
apiVersion: v1
kind: Service
metadata:
  name: placeholder-service
spec:
  type: NodePort
  selector:
    app: placeholder
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30080
