- name: Configure EC2 for Ethereum & Kubernetes
  hosts: all
  become: true
  gather_facts: false

  pre_tasks:
    - name: Wait 10 seconds before connecting (instance stabilization)
      pause:
        seconds: 10

  tasks:

    - name: Install required packages
      apt:
        name:
          - curl
          - unzip
          - software-properties-common
          - docker.io
        state: present
        update_cache: yes
        force_apt_get: yes
      environment:
        DEBIAN_FRONTEND: noninteractive

    - name: Start and enable Docker
      systemd:
        name: docker
        state: started
        enabled: true

    - name: Add ubuntu user to docker group
      user:
        name: ubuntu
        groups: docker
        append: yes

    - name: Run Ethereum Geth Node in Docker
      community.docker.docker_container:
        name: ethereum-node
        image: ethereum/client-go
        state: started
        restart_policy: always
        published_ports:
          - "8545:8545"
          - "30303:30303"
        command: '--http --http.addr "0.0.0.0" --http.api "eth,net,web3"'

    - name: Install Node.js (16.x)
      shell: |
        curl -fsSL https://deb.nodesource.com/setup_16.x | bash -
        apt-get install -y nodejs
      environment:
        DEBIAN_FRONTEND: noninteractive

    - name: Install Hardhat globally
      shell: |
        npm install -g hardhat

    - name: Install Kubernetes (K3s - lightweight)
      shell: |
        curl -sfL https://get.k3s.io | sh -
      args:
        creates: /usr/local/bin/k3s

    - name: Symlink kubectl for ease of use
      file:
        src: /usr/local/bin/k3s
        dest: /usr/local/bin/kubectl
        state: link
        force: yes

    - name: Install Helm
      shell: |
        curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash

    - name: Add HashiCorp Helm repository
      shell: helm repo add hashicorp https://helm.releases.hashicorp.com

    - name: Update Helm repositories
      shell: helm repo update

    - name: Create vault namespace
      shell: kubectl create namespace vault --dry-run=client -o yaml | kubectl apply -f -

    - name: Wait for K3s to become ready
      shell: |
        echo "⏳ Waiting for K3s to be ready..."
        for i in {1..30}; do
          if kubectl get nodes &> /dev/null; then
            echo "✅ K3s is ready!"
            exit 0
          else
            echo "Still waiting... attempt $i"
            sleep 10
          fi
        done
        echo "❌ K3s did not become ready in time"
        exit 1
      register: k3s_ready
      failed_when: k3s_ready.rc != 0

    - name: Deploy Vault via Helm
      shell: |
        helm install vault hashicorp/vault --namespace vault --set "server.dev.enabled=true"
      register: vault_helm
      retries: 3
      delay: 15
      until: vault_helm.rc == 0
