- name: Wait for SSH to become available
  hosts: all
  gather_facts: no
  tasks:
    - name: Wait for port 22 (SSH) to be open
      wait_for:
        host: '{{ inventory_hostname }}'
        port: 22
        timeout: 180

- name: Configure EC2 for Ethereum & Kubernetes
  hosts: all
  become: yes
  tasks:
    - name: Update and install required packages
      apt:
        update_cache: yes
        name:
          - curl
          - unzip
          - software-properties-common

    - name: Install Docker
      shell: |
        sudo apt update
        sudo apt install -y docker.io
        sudo systemctl start docker
        sudo systemctl enable docker
        sudo usermod -aG docker ubuntu

    - name: Install Ethereum Geth Node in Docker
      shell: |
        sudo docker run -d --name ethereum-node -p 8545:8545 -p 30303:30303 ethereum/client-go --http --http.addr "0.0.0.0" --http.api "eth,net,web3"

    - name: Install Node.js and Hardhat
      shell: |
        curl -fsSL https://deb.nodesource.com/setup_16.x | sudo -E bash -
        sudo apt install -y nodejs
        sudo npm install -g hardhat

    - name: Install Kubernetes (K3s)
      shell: |
        curl -sfL https://get.k3s.io | sh -

    - name: Deploy Vault on Kubernetes
      shell: |
        kubectl apply -f https://raw.githubusercontent.com/hashicorp/vault-k8s/main/deploy/vault.yaml
