- name: Configure EC2 for Ethereum & Kubernetes
  hosts: all
  become: false
  gather_facts: false

  pre_tasks:
    - name: Wait 30 seconds before connecting (instance stabilization)
      pause:
        seconds: 15

  tasks:
    - name: Basic stability check
      shell: uptime

    - name: Simple Docker install
      apt:
        name: docker.io
        state: present
        update_cache: yes

    - name: Start Docker service
      systemd:
        name: docker
        state: started
        enabled: yes
