- name: Configuring EC2 instance 
  hosts: all
  become: true
  gather_facts: false

  pre_tasks:
    - name: Wait for EC2 to stabilize
      pause:
        seconds: 15

  tasks:
    - name: Install essential packages
      apt:
        name:
          - curl
          - unzip
          - docker.io
          - apt-transport-https
          - ca-certificates
          - gnupg
        state: present
        update_cache: yes
      environment:
        DEBIAN_FRONTEND: noninteractive

    - name: Start and enable Docker
      systemd:
        name: docker
        state: started
        enabled: true

    - name: Add ubuntu user to docker group
      user:
        name: ubuntu
        groups: docker
        append: yes

    - name: Deploy Ethereum Geth Node in Docker
      docker_container:
        name: ethereum-node
        image: ethereum/client-go
        state: started
        restart_policy: always
        published_ports:
          - "8545:8545"
          - "30303:30303"
        command: '--http --http.addr "0.0.0.0" --http.api "eth,net,web3"'

    - name: Install Node.js (16.x)
      shell: |
        curl -fsSL https://deb.nodesource.com/setup_16.x | bash -
        apt-get install -y nodejs
      environment:
        DEBIAN_FRONTEND: noninteractive

    - name: Install Hardhat globally
      npm:
        name: hardhat
        global: yes

    - name: Install K3s Kubernetes
      shell: |
        curl -sfL https://get.k3s.io | sh -
      args:
        creates: /usr/local/bin/k3s

    - name: Symlink K3s as kubectl
      file:
        src: /usr/local/bin/k3s
        dest: /usr/local/bin/kubectl
        state: link
        force: yes

    - name: Deploy Placeholder App on K3s
      copy:
        src: ../app/fundraiser.yaml
        dest: /home/ubuntu/fundraiser.yaml
        mode: '0644'

    - name: Apply K8s manifest using kubectl
      shell: |
        kubectl apply -f /home/ubuntu/fundraiser.yaml
