- name: Configure EC2 for Ethereum & Kubernetes
  hosts: all
  become: true
  gather_facts: false

  pre_tasks:
    - name: Wait 10 seconds before connecting (instance stabilization)
      pause:
        seconds: 10

  tasks:
    - name: Simple Docker install
      apt:
        name: docker.io
        state: present
        update_cache: yes
      environment:
        DEBIAN_FRONTEND: noninteractive

    - name: Start Docker service
      systemd:
        name: docker
        state: started
        enabled: yes

    - name: Run Ethereum Geth Node in Docker
      community.docker.docker_container:
        name: ethereum-node
        image: ethereum/client-go
        state: started
        restart_policy: always
        published_ports:
          - "8545:8545"
          - "30303:30303"
        command: '--http --http.addr "0.0.0.0" --http.api "eth,net,web3"'

    - name: Install Node.js (16.x)
      shell: |
        curl -fsSL https://deb.nodesource.com/setup_16.x | bash -
        apt-get install -y nodejs
      environment:
        DEBIAN_FRONTEND: noninteractive

    - name: Install Hardhat globally
      shell: |
        npm install -g hardhat
