- name: Configure EC2 for Ethereum & Kubernetes
  hosts: all
  become: true
  gather_facts: false

  pre_tasks:
    - name: Wait for instance to be reachable via SSH (180 seconds max)
      wait_for_connection:
        timeout: 180

  tasks:
    - name: Update all packages to latest version (stable)
      apt:
        upgrade: dist
        update_cache: yes
        force_apt_get: yes
      environment:
        DEBIAN_FRONTEND: noninteractive
      register: apt_result
      retries: 3
      delay: 30
      until: apt_result is succeeded

    - name: Install required packages (curl, unzip, software-properties-common)
      apt:
        name:
          - curl
          - unzip
          - software-properties-common
        state: present
        update_cache: yes
        force_apt_get: yes
      environment:
        DEBIAN_FRONTEND: noninteractive

    - name: Install Docker (stable approach)
      apt:
        name: docker.io
        state: present
        force_apt_get: yes
      environment:
        DEBIAN_FRONTEND: noninteractive
      notify: 
        - enable docker service
        - add ubuntu user to docker group

    - name: Install Ethereum Geth Node container
      community.docker.docker_container:
        name: ethereum-node
        image: ethereum/client-go
        state: started
        restart_policy: always
        published_ports:
          - "8545:8545"
          - "30303:30303"
        command: '--http --http.addr "0.0.0.0" --http.api "eth,net,web3"'

    - name: Install Node.js (16.x) and npm global packages
      shell: |
        curl -fsSL https://deb.nodesource.com/setup_16.x | bash -
        apt-get install -y nodejs
        npm install -g hardhat
      environment:
        DEBIAN_FRONTEND: noninteractive

    - name: Install Kubernetes (K3s - lightweight)
      shell: |
        curl -sfL https://get.k3s.io | sh -
      args:
        creates: /usr/local/bin/k3s

    - name: Ensure kubectl is symlinked
      file:
        src: /usr/local/bin/k3s
        dest: /usr/local/bin/kubectl
        state: link
        force: yes

    - name: Deploy Vault on Kubernetes (using stable manifest)
      shell: |
        kubectl apply -f https://raw.githubusercontent.com/hashicorp/vault-k8s/main/deploy/vault-operator.yaml
      register: vault_deploy
      retries: 3
      delay: 10
      until: vault_deploy.rc == 0

  handlers:
    - name: enable docker service
      systemd:
        name: docker
        state: started
        enabled: yes

    - name: add ubuntu user to docker group
      user:
        name: ubuntu
        groups: docker
        append: yes
