- name: Configure EC2 for Ethereum & Kubernetes
  hosts: all
  become: true
  gather_facts: false

  pre_tasks:
    - name: Wait 5 seconds before connecting (instance stabilization)
      pause:
        seconds: 10

  tasks:

    - name: Simple Docker install
      apt:
        name: docker.io
        state: present
        update_cache: yes
      environment:
        DEBIAN_FRONTEND: noninteractive

    - name: Start Docker service
      systemd:
        name: docker
        state: started
        enabled: yes
