name: CI/CD Pipeline for Blockchain Setup

on:
  push:
    branches:
      - master
  delete:
    branches:
      - master

jobs:
  terraform:
    runs-on: ubuntu-latest
    outputs:
      ec2_ip: ${{ steps.get_ip.outputs.ec2_ip }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.5.5

      - name: Initialize Terraform
        run: terraform init
        working-directory: terraform
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Apply Terraform Configuration
        run: terraform apply -auto-approve
        working-directory: terraform
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Get EC2 Public IP
        id: get_ip
        run: |
          EC2_IP=$(terraform output -raw geth_public_ip)
          echo "ec2_ip=$EC2_IP" >> $GITHUB_OUTPUT
        working-directory: terraform
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

  ansible:
    needs: terraform
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install SSH & Ansible
        run: |
          sudo apt update
          sudo apt install -y ansible openssh-client

      - name: Configure SSH Key (Debug)
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" | sed 's/\r$//' > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
    
          echo "Checking EC2 IP:"
          echo "${{ needs.terraform.outputs.ec2_ip }}"

          echo "Testing if SSH port is reachable:"
          nc -zv ${{ needs.terraform.outputs.ec2_ip }} 22

          echo "Adding EC2 to known_hosts:"
          ssh-keyscan -v -H ${{ needs.terraform.outputs.ec2_ip }} >> ~/.ssh/known_hosts

          echo "Testing direct SSH Connection:"
          ssh -o StrictHostKeyChecking=no ubuntu@${{ needs.terraform.outputs.ec2_ip }} "echo SSH connection successful"

      - name: Verify SSH Connection
        run: |
          echo "Testing SSH connection to EC2..."
          ssh -o StrictHostKeyChecking=no ubuntu@${{ needs.terraform.outputs.ec2_ip }} "echo '✅ SSH Connection Successful'"

      - name: Generate Dynamic Ansible Inventory
        run: |
          echo "[ethereum]" > ansible/inventory.ini
          echo "${{ needs.terraform.outputs.ec2_ip }} ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/id_rsa" >> ansible/inventory.ini

      - name: Run Ansible Playbook
        run: ansible-playbook -i ansible/inventory.ini ansible/setup.yml

  destroy:
    if: github.event_name == 'delete' && github.event.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.5.5

      - name: Destroy Infrastructure
        run: terraform destroy -auto-approve
        working-directory: terraform
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
